name: Update Climate Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs once a day

jobs:
  update-climate-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch Climate Data
      id: fetch_data
      run: |
        # Fetch climate data using curl or another method
        # For this example, assume you get the data from a JSON API
        climate_clock_data=$(curl -s "https://api.climateclock.world/api/v1/climate-data")
        renewables_percent=$(curl -s "https://api.climateclock.world/api/v1/renewables-percent")
        
        # Calculate years, months, and days left for climate deadline
        # This is a simplified approach, modify it according to the API data
        deadline_timestamp="2029-07-22T16:00:00+00:00"
        current_timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        deadline_diff=$(( $(date -d "$deadline_timestamp" +%s) - $(date -d "$current_timestamp" +%s) ))
        years_left=$(( deadline_diff / 31536000 ))  # 60 seconds * 60 minutes * 24 hours * 365 days
        months_left=$(( (deadline_diff % 31536000) / 2592000 ))  # 60 seconds * 60 minutes * 24 hours * 30 days
        days_left=$(( (deadline_diff % 2592000) / 86400 ))  # 60 seconds * 60 minutes * 24 hours

        # Save the values to be used later in the workflow
        echo "years_left=$years_left" >> $GITHUB_ENV
        echo "months_left=$months_left" >> $GITHUB_ENV
        echo "days_left=$days_left" >> $GITHUB_ENV
        echo "renewables_percent=$renewables_percent" >> $GITHUB_ENV

    - name: Update README with new data
      run: |
        # Read the current README file
        readme_file="README.md"
        climate_clock_content="Time Left to Limit Global Warming: ${{ env.years_left }} years, ${{ env.months_left }} months, ${{ env.days_left }} days"
        renewables_content="Global Renewables Percentage: ${{ env.renewables_percent }}%"

        # Replace old content (if any) with the new climate clock and renewables data
        sed -i "s|<!-- climate clock time start -->.*<!-- climate clock time end -->|<!-- climate clock time start -->$climate_clock_content<!-- climate clock time end -->|" $readme_file
        sed -i "s|<!-- renewables percentage start -->.*<!-- renewables percentage end -->|<!-- renewables percentage start -->$renewables_content<!-- renewables percentage end -->|" $readme_file

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        git commit -m "Update climate data"
        git push
