name: Update README with Climate Clock

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day

permissions: write-all  # Ensure the necessary permissions to push to the repo

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch Climate Clock data
      run: |
        curl -s https://api.climateclock.world/v2/widget/clock.json > clock_data.json

    - name: Extract data and update README
      run: |
        carbon_deadline_timestamp=$(jq -r '.data.modules.carbon_deadline_1.timestamp' clock_data.json)
        current_date=$(date +%s)
        carbon_deadline_seconds=$(date -d $carbon_deadline_timestamp +%s)
        time_remaining_seconds=$((carbon_deadline_seconds - current_date))

        years=$((time_remaining_seconds / 31556952))
        months=$(((time_remaining_seconds % 31556952) / 2629746))
        days=$(((time_remaining_seconds % 2629746) / 86400))
        time_remaining_formatted="${years} years, ${months} months, ${days} days"

        renewables_percentage=$(jq -r '.data.modules.renewables_1.initial' clock_data.json)

        top_news=$(jq -r '.data.modules.newsfeed_1.newsfeed[0:5] | map("* [\(.headline)](\(.link)): \(.source)") | join("\n")' clock_data.json)

        escaped_time_remaining=$(echo "$time_remaining_formatted" | sed 's/[&/\]/\\&/g')
        escaped_renewables_percentage=$(echo "$renewables_percentage" | sed 's/[&/\]/\\&/g')
        escaped_top_news=$(echo "$top_news" | sed 's/[&/\]/\\&/g')

        # Escape newlines in the news content for proper formatting
        escaped_top_news=$(echo "$escaped_top_news" | sed ':a;N;$!ba;s/\n/\\n/g')

        # Remove old content
        sed -i '/<!-- climate clock time start -->/,+1d' profile/README.md
        sed -i '/<!-- renewable energy percentage start -->/,+1d' profile/README.md
        sed -i '/<!-- renewable energy percentage end -->/,+1d' profile/README.md
        sed -i '/<!-- climate clock news start -->/,+1d' profile/README.md
        sed -i '/<!-- climate clock news end -->/,+1d' profile/README.md

        # Insert new content
        sed -i "/<!-- climate clock time start -->/a\
Time Left to Limit Global Warming: $escaped_time_remaining" profile/README.md

        sed -i "/<!-- renewable energy percentage start -->/a\
Renewable Energy Share: $escaped_renewables_percentage%" profile/README.md

        sed -i "/<!-- climate clock news start -->/a\
$escaped_top_news" profile/README.md

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v7
      with:
        message: "Update README with latest Climate Clock data and top news"
        add: "profile/README.md"
        author_name: "GitHub Actions"
        author_email: "github-actions@github.com"
        push: true
