name: Update README with Climate Clock

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day

permissions: write-all  # Ensure the necessary permissions to push to the repo

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch Climate Clock data
      run: |
        curl -s https://api.climateclock.world/v2/widget/clock.json > clock_data.json

    - name: Extract data and update README
      run: |
        # Extract the remaining time to limit global warming
        time_remaining=$(jq -r '.data.modules.carbon_deadline_1.timestamp' clock_data.json)
        time_left_formatted=$(date -d $time_remaining "+%B %d, %Y")

        # Format the top news as Markdown links
        top_news=$(jq -r '.data.modules.newsfeed_1.newsfeed[0:5] | map("• [\(.headline)](\(.link))") | join("\n")' clock_data.json)

        # Escape special characters in time and news
        escaped_time_left=$(echo "$time_left_formatted" | sed 's/[&/\]/\\&/g')
        escaped_top_news=$(echo "$top_news" | sed 's/[&/\]/\\&/g')

        # Escape newlines for insertion into the README
        escaped_top_news=$(echo "$escaped_top_news" | sed ':a;N;$!ba;s/\n/\\n/g')

        # Replace placeholders in the README with the extracted data
        perl -pi -e "s|<!-- CLIMATE_CLOCK_TIME_REMAINING -->|Time Left to Limit Global Warming: $escaped_time_left|" profile/README.md
        perl -pi -e "s|<!-- CLIMATE_NEWS_TOP_5 -->|$escaped_top_news|" profile/README.md

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v7
      with:
        message: "Update README with latest Climate Clock data and top news"
        add: "profile/README.md"
        author_name: "GitHub Actions"
        author_email: "github-actions@github.com"
        push: true
