name: Update README with Climate Clock and News

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq (if not already installed)
      run: |
        sudo apt-get update
        sudo apt-get install jq

    - name: Fetch Climate Clock data
      run: |
        curl -s https://api.climateclock.world/v2/widget/clock.json > clock_data.json

    - name: Extract data and update README
      run: |
        # Extracting Time Left to 1.5°C and the Top 5 News
        time_remaining=$(jq -r '.data.modules.carbon_deadline_1.timestamp' clock_data.json)
    
        time_remaining_unix=$(date -d "$time_remaining" +%s)
    
        time_left_formatted=$(date -d @$time_remaining_unix "+%B %d, %Y")
    
        top_news=$(jq -r '.data.modules.newsfeed_1.newsfeed[0:5] | map("• \(.headline) - \(.source) (\(.link))") | join("\n")' clock_data.json)

        sed -i "s|<!-- CLIMATE_CLOCK_TIME_REMAINING -->|Time Left to Limit Global Warming: $time_left_formatted|" README.md
        sed -i "s|<!-- CLIMATE_NEWS_TOP_5 -->|$top_news|" README.md

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v7
      with:
        message: "Update README with latest Climate Clock data and top news"
        add: "profile/README.md"
